# Generated by Django 5.1.3 on 2024-11-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='middle_name',
            new_name='last_name',
        ),
    ]
